name: Test & Deploy Documentation
on: [push, pull_request]
env:
  NODE_BUILD_VERSION: 12.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_BUILD_VERSION }}
    - run: npm ci
    - run: npm run lint
    - run: npm test

  package:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_BUILD_VERSION }}

      - run: npm ci
      - run: npm version prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version
      - run: npm pack
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
            name: package
            path: "*.tgz"

  publish:
    name: "Publish to GitHub Packages"
    needs: [ package ]
    runs-on: ubuntu-latest
    if: github.repository_owner == 'tdilauro'
    steps:
      - name: Upload
        uses: actions/download-artifact@v2
        with:
          name: package
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_BUILD_VERSION }}
          registry-url: https://npm.pkg.github.com/
          scope: "@${{ github.repository_owner }}"
      - run: echo "registry=https://npm.pkg.github.com/@${{ github.repository_owner }}" >> .npmrc
      - run: npm publish $(ls *.tgz)
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
